### PR TITLE
Creating a CSR for an encrypted key

### PR DESCRIPTION
**Pull request by DullReferenceException**
Added the ability to specify the password for a private key when creating a CSR.

### CODE REVIEW

**Comment by Dexus** [comment]
Hi @DullReferenceException 

please use for all passwords the `file:tmp_passwd_file.xxx` instand `pass:my!secure"password`
and create the file with the password as content

**Comment by DullReferenceException** [comment]
Very good point. I'll work on that.

**Comment by DullReferenceException** [comment]
Strangely, I can't get openssl to break with any input. Seems like `spawn` is doing all the right things when it comes to escaping the argument. Here's a sample of what I've tried:

```
var password = 'my:secure! "password';
```

**Comment by Dexus** [comment]
Okay, i will try it tomorrow again, perhaps i have make a misstake.

**Comment by DullReferenceException** [comment]
I finally broke it by having an `\n` in the password. Will try using the temporary file to pass the password and see if the tests pass.

**Comment by DullReferenceException** [comment]
@Dexus: fixed to write to the temporary file using the same pattern as when generating an encrypted private key.

**Comment by Dexus** [comment]
@DullReferenceException you need to unlink the tempfile see my commend

**Comment by DullReferenceException** [comment]
Fixed, @Dexus.

**Pull request merged**
