### PR TITLE
Change SAN CSR process.

### PR DESCRIPTION
**Pull request by Dexus**
Now the OpenSSL configuration file is created correctly.

Look: https://github.com/andris9/pem/pull/10#issuecomment-37906170

### CODE REVIEW

**Comment by andris9** [comment]
Thanks! I would prefer if you used native [isIPv4](http://nodejs.org/api/net.html#net_net_isipv4_input) and [isIPv6](http://nodejs.org/api/net.html#net_net_isipv6_input) methods though or is there a reason for using your own?

**Comment by Dexus** [comment]
You're right, sometimes I make life difficult for me.

**Comment by andris9** [comment]
You have an undefined `isIPv4` in the commit, replace it with `net.isIPv4`.

And just for the reference, you can always edit your pull request with `git rebase` which allows you to combine several commits into one final commit. If you do this while the PR is not accepted yet, it also modifies the PR in Github.

Run `git rebase -i ZZZ` where ZZZ is the last commit you do not want to touch. In the opened editor keep the first `pick` but replace all the next `pick` terms with `squash`. Save and exit. Next the commit message editor appears. You can edit it but this is not mandatory. Save and exit. Next push the commit with `-f` flag (as you modified the history, Github will not accept the update by default, you need to force push) `git push origin master -f`

**Comment by Dexus** [comment]
Thank You for the hint.

Hope all clean now.

**Comment by andris9** [comment]
Thanks!

**Comment by Dexus** [comment]
You're Welcome!

**Pull request merged**
