### PR TITLE
add 3 fields to certificate parsing

### PR DESCRIPTION
**Pull request by TatyanaBol**
Dear Josef
We are happy to find your package that implement all requirements we need to parse and validate SSL certificate in PEM format. It's very clear and convenient.
The only thing we miss here is 3 certificate's fields - signatureAlgorithm, publicKeyAlgorithm and publicKeySize. Please add them to the implementation of fetchCertificateData.

Thanks in advance,
Tatyana Bolshinsky
Senior Software Developer
IBM Cloud Security Team

### CODE REVIEW

**Comment by Dexus** [comment]
Dear Tatyana,
I'm happy to read that you are happy with this package.

I thank you for your PR. Feel free to open an other PR for your needs.

Regards,
Josef Fröhle

**Comment by TatyanaBol** [comment]
Dear Josef
Thank you for your answer.
When are you planning to publish a new version to npm?
We can use your package only from there.

Best regards,
Tatyana

**Comment by Dexus** [comment]
Yes, planing to but the automation was broken... will publish it tomorrow manually. 

Von meinem iPhone gesendet

**Comment by TatyanaBol** [comment]
Nice!!
Thanks!
Tatyana

**Comment by Dexus** [comment]
@TatyanaBol released sorry for the delay

**Comment by TatyanaBol** [comment]
Thanks!

**Comment by TatyanaBol** [comment]
Hi
I found a problem with parsing Public Key Size in different OS.
Apparently openssl works differently and the field looks different.
On my Mac it looks '**RSA Public key: (2048 bit)**'.
On Linux machine it looks like '**Public-Key: (2048 bit)**'.
So I changed a little parsing for this field.
Please review and merge my Pull Request

Tatyana

**Pull request merged**
