### PR TITLE
Add getDhparamInfo

### PR DESCRIPTION
**Pull request by silverwind**
io.js 2.1.0 enforces a minimum DH size of 1024 (https://github.com/nodejs/io.js/commit/9b35be58100237365c24ab394d3dc6462f9675e6), which created a need for me to have a method to check the key size. I also included the prime itself in the callback.

### CODE REVIEW

**Comment by silverwind** [comment]
In case you're wondering about that CI failure on io.js: https://github.com/nodejs/io.js/issues/1850

**Comment by Dexus** [comment]
Thank you, i'll review it and than commit.

**Comment by silverwind** [comment]
Updated the test to check for 1024 bit size.

**Comment by Dexus** [comment]
Will be merged soon.

**Pull request closed without merging**
