### PR TITLE
fix readCertificateInfo for the case when cert subject is empty

### PR DESCRIPTION
**Pull request by TatyanaBol**
Solution for issue #263

### CODE REVIEW

**Comment by TatyanaBol** [comment]
@Dexus Can you please check why did the build fail?
I don't think it's because of my changes.

**Comment by Dexus** [comment]
@TatyanaBol it fails because of CI different NPM.

**Comment by IdanAdar** [comment]
@Dexus Can you release a new version with this fix to NPM registry?

**Comment by ArikShifer** [comment]
@Dexus Can you please fix it. See:  https://travis-ci.community/t/npm-ci-will-fail-if-cached-dependency-includes-npm/4203

**Comment by TatyanaBol** [comment]
Thank you for your quick response!


Tatyana Bolshinsky  | Senior Program Developer
IBM Cloud Security Tel +972-9-952-5683

**Pull request merged**
