### PR TITLE
Added functionality to get modulus from a  password protected key

### PR DESCRIPTION
**Pull request by debonair**
Please review and merge this pull request

### CODE REVIEW

**Comment by Dexus** [comment]
Hi @debonair: please see my notice.

**Comment by debonair** [comment]
@Dexus I have fixed the issue.

**Comment by debonair** [comment]
@Dexus have you had a chance to review this pull request?

**Comment by Dexus** [comment]
Hi duma, i can only review it next week, have much work …

Von meinem iPhone gesendet

**Comment by debonair** [comment]
OK no problem when you get a chance, I have some code that depends on this on another opensource project I am working on

**Comment by Dexus** [comment]
I will release a new version end of the week, have to change some code and docs.

**Comment by debonair** [comment]
Cool thanks

**Pull request merged**
