### PR TITLE
altNames option to set subjectAltName

### PR DESCRIPTION
**Pull request by dodo**
option to create a config with a subjectAltName field.

### CODE REVIEW

**Comment by andris9** [comment]
Thanks!

**Comment by Dexus** [comment]
Wrong implemented!

```
[req]
req_extensions     = v3_req
distinguished_name = req_distinguished_name
[v3_req]
subjectAltName = @alt_names
[alt_names]
www.domain.eu
www.domain.com
www.domain.de
[req_distinguished_name]
commonName     = Common Name
commonName_max = 64
```

MUST BE:

```
[req]
req_extensions     = v3_req
distinguished_name = req_distinguished_name
[v3_req]
subjectAltName = @alt_names
[alt_names]
DNS.1 = www.domain.eu
DNS.2 = www.domain.com
DNS.3 = www.domain.de
[req_distinguished_name]
commonName     = Common Name
commonName_max = 64
```

Either it should be documented, that the DNS.1 .. 99 with equal sign prefixing the domain name or you have to rewrite the script to do it.

I do not know what you prefer, but I find the solution directly in the script better.

**Comment by dodo** [comment]
it's not wrong implement, but rather _not_ implemented :)

what you did there was:

``` javascript
{ altNames:[
    'www.domain.eu',
    'www.domain.com',
    'www.domain.de'
]}
```

what you could have done:

``` javascript
{ altNames:[
    'DNS.1 = www.domain.eu',
    'DNS.2 = www.domain.com',
    'DNS.3 = www.domain.de'
]}
```

anyway, +1  for your PR (:

**Comment by Dexus** [comment]
@dodo ty :)

**Pull request merged**
