### PR TITLE
Added noop callback (Node 7.0 deprecation warning)

### PR DESCRIPTION
**Pull request by vizo**

### CODE REVIEW

**Comment by gajus** [comment]
@andris9 can you please merge this?

although, I'd like this to throw an error if there is an error.

**Comment by gajus** [comment]
@andris9 Please release this change. Its flooding logs at the moment.

**Comment by andris9** [comment]
@gajus  You have to ask @Dexus as he is doing the releases

**Comment by gajus** [comment]
@Dexus can you please do the release?

It would be nice to add either more people to NPM or use something like https://github.com/semantic-release/semantic-release to automate the release process.

**Comment by Dexus** [comment]
Yeah i will do, but currently i'm on a business trip so it will maybe two weeks. Have here no key for my system.

Regards,
Josef

Von meinem iPhone gesendet

**Comment by gajus** [comment]
> Yeah i will do, but currently i'm on a business trip so it will maybe two weeks. Have here no key for my system.

Can you add me as a collaborator to NPM? This can be done via the web UI. My username is "gajus".

**Comment by Dexus** [comment]
From here i'm also unable to login to NPM. I have only my work laptop and not access to any private keys and passwords.

Regards, Josef

Von meinem iPhone gesendet

**Pull request merged**
